/*
  Entertainment-first channel blocklist for local recommendation filtering.
  Source references used to seed this list (accessed on 2026-02-15):
  - https://socialblade.com/youtube/top/100
  - https://en.wikipedia.org/wiki/List_of_most-subscribed_YouTube_channels
*/
(function () {
  const channels = [
    "MrBeast",
    "T-Series",
    "Cocomelon - Nursery Rhymes",
    "SET India",
    "Vlad and Niki",
    "Kids Diana Show",
    "Stokes Twins",
    "Like Nastya",
    "KIMPRO",
    "Zee Music Company",
    "WWE",
    "PewDiePie",
    "Goldmines",
    "Sony SAB",
    "Alejo Igoa",
    "BLACKPINK",
    "Alan's Universe",
    "ChuChu TV Nursery Rhymes & Kids Songs",
    "Zee TV",
    "A4",
    "Baby Shark - Pinkfong Kids' Songs & Stories",
    "Topper Guild",
    "BANGTANTV",
    "Toys and Colors",
    "Colors TV",
    "Tips Official",
    "LooLoo Kids - Nursery Rhymes and Children's Songs",
    "El Reino Infantil",
    "Justin Bieber",
    "HYBE LABELS",
    "Shemaroo Filmi Gaane",
    "5-Minute Crafts",
    "Badabun",
    "Luisito Comunica",
    "Sony PAL",
    "EminemMusic",
    "YRF",
    "Wave Music",
    "HAR PAL GEO",
    "Dude Perfect",
    "Sony Music India",
    "KL BRO Biju Rithvik",
    "Billion Surprise Toys - English Kids Songs & Cartoons",
    "Taylor Swift",
    "Marshmello",
    "Movieclips",
    "Masha and The Bear",
    "Toys and Colors Playhouse",
    "Katy Perry",
    "Mikecrack",
    "Billie Eilish",
    "Ariana Grande",
    "Fede Vigevani",
    "Get Movies",
    "Dangal TV Channel",
    "Alfredo Larin",
    "Kim Loaiza",
    "JuegaGerman",
    "Jess No Limit",
    "LankyBox",
    "ABS-CBN Entertainment",
    "DaFuq!?Boom!",
    "LUCCAS NETO - LUCCAS TOON",
    "Goldmines Gaane Sune Ansune",
    "Annie's Magic Show",
    "Frost Diamond",
    "Sierra & Rhia FAM",
    "Genevieve's Playhouse - Learning Videos for Kids",
    "BeatboxJCOP",
    "Karla Bustillos",
    "Felipe Neto",
    "JioHotstar Kids",
    "Galinha Pintadinha",
    "Desi Music Factory",
    "Ishtar Music",
    "Toys and Fruits",
    "JoJo Siwa",
    "Speed Records",
    "Goldmines Action",
    "BRIGHT SIDE",
    "Aaj Tak",
    "StarPlus",
    "Sony Entertainment Television",
    "Shemaroo",
    "B4U Music",
    "Saregama Music",
    "Sun TV",
    "Rajshri",
    "Geo TV",
    "Hum TV",
    "ARY Digital HD",
    "Anaya Kandhal",
    "Anaya's World",
    "Kids Roma Show",
    "Ryan's World",
    "BabyBus - Kids Songs and Cartoons",
    "Blippi",
    "Pinkfong Baby Shark",
    "CoComelon JJ's Animal Time",
    "Nastya and Dad",
    "Ninja Kidz TV",
    "Nisha Madhulika Shorts",
    "CarryMinati",
    "Total Gaming",
    "Techno Gamerz",
    "Triggered Insaan",
    "Mythpat",
    "Ashish Chanchlani Vines",
    "Round2hell",
    "BB Ki Vines",
    "Bhuvan Bam",
    "The RawKnee Games",
    "Mortal",
    "Scout",
    "Jonathan Gaming",
    "Dynamo Gaming",
    "Mr Indian Gamer",
    "RakaZone Gaming",
    "S8UL",
    "TheBongGuy",
    "Slayy Point",
    "Elvish Yadav",
    "Fukra Insaan",
    "MrBallen",
    "Sidemen",
    "KSI",
    "Logan Paul",
    "Jake Paul",
    "Markiplier",
    "jacksepticeye",
    "DanTDM",
    "VanossGaming",
    "SSSniperWolf",
    "Unspeakable",
    "Preston",
    "Dream",
    "Aphmau",
    "Ninja",
    "LazarBeam",
    "FaZe Rug",
    "FaZe Clan",
    "CoryxKenshin",
    "TheDonato",
    "Fernanfloo",
    "Vegetta777",
    "AuronPlay",
    "Rubius Z",
    "Ibai",
    "DrossRotzank",
    "Germn",
    "HolaSoyGerman",
    "Werevertumorro",
    "Yuya",
    "Lele Pons",
    "NikkieTutorials",
    "Roman Atwood",
    "Casey Neistat",
    "David Dobrik",
    "MrSuicideSheep",
    "Trap Nation",
    "Spinnin' Records",
    "Ultra Records",
    "Monstercat",
    "NoCopyrightSounds",
    "Vevo",
    "Ed Sheeran",
    "Adele",
    "Bruno Mars",
    "Shakira",
    "BTS",
    "BLACKPINK GLOBAL",
    "JYP Entertainment",
    "SMTOWN",
    "KBS WORLD TV",
    "Mnet K-POP",
    "Shemaroo Comedy",
    "Taarak Mehta Ka Ooltah Chashmah",
    "The Kapil Sharma Show",
    "Comedy Central India",
    "CollegeHumor",
    "FailArmy",
    "The Try Guys",
    "H2ODelirious",
    "The Game Theorists",
    "The Film Theorists",
    "WatchMojo",
    "Screen Rant",
    "Looper",
    "IGN",
    "GameSpot",
    "Polygon",
    "Fandango",
    "Paramount Movies",
    "Sony Pictures Entertainment",
    "Universal Pictures",
    "Warner Bros. Pictures",
    "Marvel Entertainment",
    "DC",
    "Pixar",
    "DisneyMusicVEVO"
  ];

  self.TUBEFOCUS_ENTERTAINMENT_CHANNELS = channels;
})();

